name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      # 🔥 核心：用这个，不要再用 cargo tauri
      - name: Build Tauri App
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: seacat-note-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**
                  - name: Upload Release Assets
          files: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.dmg        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}