name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # Windows 需要这个
      - name: Install Rust target (Windows only)
        if: matrix.os == 'windows-latest'
        run: rustup target add x86_64-pc-windows-msvc

      # 🔥 核心：直接用 cargo tauri build
      - name: Build Tauri App
        run: |
          cargo tauri build

      # 上传产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: seacat-note-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**